#!/bin/sh
# Add fnm to PATH and load node/pnpm environment
export PATH="/c/Users/Andrew/AppData/Local/Microsoft/WinGet/Packages/Schniz.fnm_Microsoft.Winget.Source_8wekyb3d8bbwe:$PATH"
eval "$(fnm env --shell bash)"
pnpm format:check
pnpm lint
